### ISSUE TITLE
SDK crashes

### ISSUE THREAD

**Issue by Wojtek1234** [iovation/deviceprint-SDK-Android#2]
Iovation SDK throws an exception

> Fatal Exception: java.lang.SecurityException: "network" location provider requires ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION permission.
>        at android.os.Parcel.readException(Parcel.java:1487)
>        at android.os.Parcel.readException(Parcel.java:1436)
>        at android.location.ILocationManager$Stub$Proxy.requestLocationUpdates(ILocationManager.java:540)
>        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:860)
>        at android.location.LocationManager.requestLocationUpdates(LocationManager.java:485)
>        at com.iovation.mobile.android.details.a.a.b(Unknown Source)
>        at com.iovation.mobile.android.details.i.b(Unknown Source)
>        at com.iovation.mobile.android.FraudForceManager.getBlackbox(Unknown Source)

that is a crashlitics report so there is no much to say, but it did comes out on android 4.4.2 so that is not a runtime permission issue

**Comment by mattr-io** [comment]
Hello Wojtek1234 - Thank you for the issue report. Would you please contact your iovation Customer Support representative about this.
