### ISSUE TITLE
Google Playstore showing Security Vulnerability warning

### ISSUE THREAD

**Issue by vkvashistha** [iovation/deviceprint-SDK-Android#4]
Google Playstore showing following Security Warnning:- 

Your app contains unsafe cryptographic encryption patterns. Please see this Google Help Center article for details.

Vulnerable classes:

com.iovation.mobile.android.details.u.b

SDK version : 3.1.0

**Comment by ashley-campbell-iovation** [comment]
The library has been updated, the security warning should now be mitigated. Please try upgrading to release 4.0.0.
