### ISSUE TITLE
Extreme package obfuscation causing duplicate class errors

### ISSUE THREAD

**Issue by gbak** [iovation/deviceprint-SDK-Android#5]
In older versions library (3.1.0), had package names in the classes.jar file.

inflated: com/iovation/mobile/android/a/c.class
inflated: com/iovation/mobile/android/a/a.class
inflated: com/iovation/mobile/android/a/b.class

The newest version has all the package names obfuscated.  

 inflated: a/a/a/a/a/a.class
 inflated: a/a/a/a/a/b.class
 inflated: a/a/a/a/a/c.class
 inflated: a/a/a/a/b/a.class

This conflicts with another external library within my project and it no longer builds.

Duplicate class a.a.a.a.a.b found in modules jetified-fraudforce-lib-4.1.1-release-runtime.jar (fraudforce-lib-4.1.1-release.aar) and ...

The same can be said for the other library, but what's the point in obfuscating your package names, provide at least the com/iovation.

**Comment by rio258k** [comment]
This issue definitely deserves attention.

**Comment by PDXMobileTommy** [comment]
Howdy gbak - Thank you for the issue report. The Android dev team here at iovation were notified of this Github posting through our Customer Support team and we have an engineer currently investigating the report.  
In the future, for a faster investigation and response; please work directly through your customer support representative. This will ensure that all required parties are aware of the issue and we can track the progress to an expedited resolution.  Cheers, Tommy
