### ISSUE TITLE
Multiple submissions from the same session

### ISSUE THREAD

**Issue by EralpB** [iovation/deviceprint-SDK-Android#6]
is it OK to generate the blackbox key once per session? so if user submits 2 different distinct piece of content, would it be OK to submit the same iovation key?

or must it be generated PER request (per content)?

**Comment by pandeyVishakha** [comment]
Heyy,
I also have the same questions. If user have to submit more than one review/content, one iovation key is sufficient or need to generate new iovation key for per request ?

**Comment by PDXMobileTommy** [comment]
Howdy.  Please reach out to your integration engineer for answers to these questions. They will be able to elaborate on the why you would or wouldn't want to implement something in a specific way and provide additional details as it relates to your industry.
Cheers, Tommy
